
server:
  port: 9001

spring:

#  main:
#    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    platform: mysql
#    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://192.168.246.42:3306/flowable-example?characterEncoding=UTF-8&useSSL=true
#    username: system_center
#    password: System_center#1234
    url: jdbc:mysql://127.0.0.1:3306/flowable-example?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    hikari:
      maximumPoolSize: 10
      minimumIdle: 2
      idleTimeout: 600000
      connectionTimeout: 30000
      maxLifetime: 1800000

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  gson:
    date-format: yyyy-MM-dd HH:mm:ss

flowable:
  check-process-definitions: true

